name: Build & release

on:
  push:
    paths:
      - packages/**

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build/release Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          package_manager: pnpm
          skip_package_manager_install: true
          package_root: ./packages/desktop #?

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
